2021-08-19 14:37:03,390 INFO    MainThread:45444 [internal.py:wandb_internal():91] W&B internal server running at pid: 45444, started at: 2021-08-19 14:37:00.736219
2021-08-19 14:37:03,393 INFO    WriterThread:45444 [datastore.py:open_for_write():77] open: /tmldata1/saberika/advex-uar/advex_uar/wandb/offline-run-20210819_143626-2ussoc62/run-2ussoc62.wandb
2021-08-19 14:37:03,394 DEBUG   HandlerThread:45444 [handler.py:handle_request():94] handle_request: run_start
2021-08-19 14:37:05,925 DEBUG   HandlerThread:45444 [meta.py:__init__():34] meta init
2021-08-19 14:37:05,925 DEBUG   HandlerThread:45444 [meta.py:__init__():48] meta init done
2021-08-19 14:37:05,925 DEBUG   HandlerThread:45444 [meta.py:probe():190] probe
2021-08-19 14:37:07,346 DEBUG   HandlerThread:45444 [meta.py:_setup_git():180] setup git
2021-08-19 14:37:25,240 DEBUG   HandlerThread:45444 [meta.py:_setup_git():187] setup git done
2021-08-19 14:37:25,462 DEBUG   HandlerThread:45444 [meta.py:_save_pip():52] save pip
2021-08-19 14:37:27,533 DEBUG   HandlerThread:45444 [meta.py:_save_pip():66] save pip done
2021-08-19 14:37:27,533 DEBUG   HandlerThread:45444 [meta.py:probe():231] probe done
2021-08-19 14:47:12,631 WARNING MainThread:45444 [internal.py:wandb_internal():146] Internal process interrupt: 1
2021-08-19 14:47:13,611 INFO    MainThread:45444 [internal.py:handle_exit():78] Internal process exited
