wandb inited <wandb.sdk.wandb_run.Run object at 0x7fafcae9da10> {}
Files already downloaded and verified
/opt/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:3829: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  "Default grid_sample and affine_grid behavior has changed "
Batch 0
{'std_loss': tensor(0.4696), 'std_acc': tensor(0.8594), 'adv_loss': tensor(2.5933), 'adv_acc': tensor(0.4062)}
Batch 1
{'std_loss': tensor(0.4495), 'std_acc': tensor(0.8477), 'adv_loss': tensor(2.8018), 'adv_acc': tensor(0.3828)}
Batch 2
{'std_loss': tensor(0.4353), 'std_acc': tensor(0.8568), 'adv_loss': tensor(2.7455), 'adv_acc': tensor(0.3620)}
Batch 3
{'std_loss': tensor(0.4189), 'std_acc': tensor(0.8652), 'adv_loss': tensor(2.7173), 'adv_acc': tensor(0.3691)}
Batch 4
{'std_loss': tensor(0.3814), 'std_acc': tensor(0.8781), 'adv_loss': tensor(2.6552), 'adv_acc': tensor(0.3828)}
Batch 5
{'std_loss': tensor(0.4010), 'std_acc': tensor(0.8685), 'adv_loss': tensor(2.6578), 'adv_acc': tensor(0.3776)}

Aborted!
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 1127, in emit
    StreamHandler.emit(self, record)
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 1029, in emit
    self.flush()
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 1009, in flush
    self.stream.flush()
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 2034, in shutdown
    h.close()
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 1103, in close
