2021-08-19 14:18:18,595 INFO    MainThread:26970 [internal.py:wandb_internal():91] W&B internal server running at pid: 26970, started at: 2021-08-19 14:18:17.676289
2021-08-19 14:18:18,598 DEBUG   HandlerThread:26970 [handler.py:handle_request():94] handle_request: run_start
2021-08-19 14:18:18,598 INFO    WriterThread:26970 [datastore.py:open_for_write():77] open: /tmldata1/saberika/advex-uar/advex_uar/wandb/offline-run-20210819_141743-3r7l0hyy/run-3r7l0hyy.wandb
2021-08-19 14:18:21,536 DEBUG   HandlerThread:26970 [meta.py:__init__():34] meta init
2021-08-19 14:18:21,536 DEBUG   HandlerThread:26970 [meta.py:__init__():48] meta init done
2021-08-19 14:18:21,536 DEBUG   HandlerThread:26970 [meta.py:probe():190] probe
2021-08-19 14:18:22,321 DEBUG   HandlerThread:26970 [meta.py:_setup_git():180] setup git
2021-08-19 14:18:40,994 DEBUG   HandlerThread:26970 [meta.py:_setup_git():187] setup git done
2021-08-19 14:18:41,335 DEBUG   HandlerThread:26970 [meta.py:_save_pip():52] save pip
2021-08-19 14:18:42,700 DEBUG   HandlerThread:26970 [meta.py:_save_pip():66] save pip done
2021-08-19 14:18:42,700 DEBUG   HandlerThread:26970 [meta.py:probe():231] probe done
2021-08-19 14:22:47,174 WARNING MainThread:26970 [internal.py:wandb_internal():146] Internal process interrupt: 1
2021-08-19 14:22:47,685 INFO    MainThread:26970 [internal.py:handle_exit():78] Internal process exited
